variable "vpc_name" {}
variable "cidr_vpc" {}
variable "public_subnet_name" {}
variable "private_subnet_name" {}
variable "cidr_public" {}
variable "cidr_private" {}
variable "igw_name" {}
variable "route_table_name" {}
variable "count_prod_pub_sub" {}
variable "prod_private_subnet_name" {}
variable "nat_gateway_name" {}
variable "nat_eip_name" {}
variable "route_table_name_2" {}
variable "cidr_prod_private" {}